"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-24

Hand-written (not autogenerated) so the schema is correct from the first
`alembic upgrade head` without needing a fully-installed local Python env.
Once the backend container is running, `alembic revision --autogenerate`
can be used to verify this matches app/db/models.py exactly before any
future schema change.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBEDDING_DIM = 384


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(320), nullable=False, unique=True, index=True),
        sa.Column("hashed_password", sa.String(1024), nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("is_superuser", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("is_verified", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
    )

    op.create_table(
        "resumes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), index=True),
        sa.Column("file_path", sa.String(500), nullable=False),
        sa.Column("raw_text", sa.Text, nullable=False),
        sa.Column("skills", postgresql.JSONB, server_default="[]"),
        sa.Column("education", postgresql.JSONB, server_default="[]"),
        sa.Column("experience", postgresql.JSONB, server_default="[]"),
        sa.Column("projects", postgresql.JSONB, server_default="[]"),
        sa.Column("certifications", postgresql.JSONB, server_default="[]"),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
    )

    op.create_table(
        "job_descriptions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), index=True),
        sa.Column("title", sa.String(300), nullable=False),
        sa.Column("raw_text", sa.Text, nullable=False),
        sa.Column("required_skills", postgresql.JSONB, server_default="[]"),
        sa.Column("preferred_skills", postgresql.JSONB, server_default="[]"),
        sa.Column("experience_required", sa.String(50), nullable=True),
        sa.Column("responsibilities", postgresql.JSONB, server_default="[]"),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
    )

    op.create_table(
        "ats_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("resume_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("resumes.id"), index=True),
        sa.Column("jd_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("job_descriptions.id"), index=True),
        sa.Column("match_score", sa.Float, nullable=False),
        sa.Column("matched_skills", postgresql.JSONB, server_default="[]"),
        sa.Column("missing_skills", postgresql.JSONB, server_default="[]"),
        sa.Column("experience_relevance", sa.Float, nullable=True),
        sa.Column("recommendation", sa.String(300), nullable=True),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
    )

    op.create_table(
        "tests",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("jd_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("job_descriptions.id"), index=True),
        sa.Column("resume_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("resumes.id"), index=True),
        sa.Column("questions", postgresql.JSONB, server_default="[]"),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
    )

    op.create_table(
        "test_attempts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), index=True),
        sa.Column("test_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tests.id"), index=True),
        sa.Column("answers", postgresql.JSONB, server_default="[]"),
        sa.Column("score", sa.Float, nullable=True),
        sa.Column("started_at", sa.DateTime, server_default=sa.func.now()),
        sa.Column("submitted_at", sa.DateTime, nullable=True),
    )

    op.create_table(
        "interview_sessions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), index=True),
        sa.Column("jd_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("job_descriptions.id"), index=True),
        sa.Column("status", sa.String(20), server_default="in_progress"),
        sa.Column("started_at", sa.DateTime, server_default=sa.func.now()),
        sa.Column("ended_at", sa.DateTime, nullable=True),
    )

    op.create_table(
        "interview_messages",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("interview_sessions.id"),
            index=True,
        ),
        sa.Column("role", sa.String(10), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("skill_tag", sa.String(100), nullable=True),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
    )

    op.create_table(
        "evaluations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("interview_sessions.id"),
            index=True,
        ),
        sa.Column("technical_score", sa.Float, nullable=True),
        sa.Column("communication_score", sa.Float, nullable=True),
        sa.Column("problem_solving_score", sa.Float, nullable=True),
        sa.Column("concept_understanding_score", sa.Float, nullable=True),
        sa.Column("overall_feedback", sa.Text, nullable=True),
    )

    op.create_table(
        "skill_verification",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), index=True),
        sa.Column("skill_name", sa.String(100), nullable=False),
        sa.Column("resume_claim", sa.Boolean, server_default=sa.false()),
        sa.Column("test_score", sa.Float, nullable=True),
        sa.Column("interview_score", sa.Float, nullable=True),
        sa.Column("trust_score", sa.Float, nullable=True),
        sa.Column("flag", sa.String(50), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("skill_verification")
    op.drop_table("evaluations")
    op.drop_table("interview_messages")
    op.drop_table("interview_sessions")
    op.drop_table("test_attempts")
    op.drop_table("tests")
    op.drop_table("ats_results")
    op.drop_table("job_descriptions")
    op.drop_table("resumes")
    op.drop_table("users")
